stages:
  - debug

variables:
  GIT_STRATEGY: none

default:
  image: "codebank-nexus.cloud.frb.org/cicd-executor-ubi:19"
  tags:
    - linux
    - docker

debug:
  stage: debug
  script:
    - echo "Runner=$CI_RUNNER_DESCRIPTION"
    - echo "Server=$CI_SERVER_HOST"
    - env | grep -i proxy
    - curl -I https://$CI_SERVER_HOST